---
title: "Untitled"
format: html
---

```{r}
#| message: false
#| warning: false
library(xml2)       # read and wrangle XML
library(tidyverse)  # {purrr}, {dplyr}, {ggplot2}, {forcats}
```


```{r}
pcs_def_xsd <- "D:\\icd_10_pcs_2024\\Zip File 2 2024 Code Tables and Index\\icd10pcs_definitions.xsd"
pcs_def_xml <- "D:\\icd_10_pcs_2024\\Zip File 2 2024 Code Tables and Index\\icd10pcs_definitions_2024.xml"
def_xml <- read_xml(pcs_def_xml)
xml_to_df(def_xml)
```



```{r}
library(xmlconvert)
read_xml(example.tags)
read_xml(example.attr)
example.tags <- system.file("worldpopulation_tags.xml", package="xmlconvert")
example.attr <- system.file("worldpopulation_attr.xml", package="xmlconvert")
worldpop.tags <- xml_to_df(text = example.tags, records.tags = c("record"),
    fields = "tags", field.names = "name")
worldpop.attr <- xml_to_df(text = pcs_def_xml, records.tags = c("terms"),
    fields = "attributes")
```


```{r}
section <- xml_find_all(def_xml, "//section")
xml_attrs(section)
axis <- xml_find_all(section, "//axis")
axis
xml_children(axis)
xml_siblings(axis)
```

```{r}
section_df <- map_dfr(  # rowbind to dataframe
  c(title = "title", 
    operation = "axis", 
    terms = "terms"),
  ~xml_attr(section, .x)
)

glimpse(section_df)  # preview

xml_attr(axis, c(term = "terms"))
axis[[2]]
```







```{r}
library(xmlr)
prs <- xmlr::parse.xmlfile(pcs_def_xml)
xmlrToDataFrame(prs$getRootElement()$getChildren())
prs$initialize()
prs$getRootElement()$getChildren()
prs$getRootElement()$getChild("section")$getChild("axis")$getChildren()
prs$getRootElement()$getChild("section")$getChildren()[[1]]$getText()
prs$getRootElement()$getChild("section")$getChildren()[[2]]$getChildren()
```


```{r}
dplyr::tibble(
  section = prs$getRootElement()$getChild("section")$getChildren()[[1]]$getText(),
  operation = prs$getRootElement()$getChild("section")$getChildren()[[2]]$getText()
)
```

